"""Analysis-facing helpers for the Finals MVP notebook.

Scraping lives under ``helpers.scrape`` / ``scripts/`` and is intentionally
not imported here, so the notebook does not need Playwright or HTML caches.
"""

from helpers.boxscores import (
    ADVANCED_FEATURE_COLS,
    LEAN_MODEL_FEATURE_COLS,
    attach_advanced,
    baseline_pick,
    build_finals_series_games,
    build_top8,
    clean_boxscore,
    control_trial,
    fix_player_name_encoding,
    list_winner_csvs,
    load_advanced_features,
    load_winner_csv,
    normalize_player_name,
    rank_table,
    select_model_features,
    series_games_from_boxscore,
    series_games_from_year,
    top_table_from_csv,
)
from helpers.features import analytic, softmax_shares, z_col, zCol
from helpers.images import fetch_image, name_img
from helpers.meta import (
    abbrev_from_team,
    champ_from_year,
    latest_finals_year,
    logo,
    logo_from_seasons_csv,
    logo_from_team_name,
    mvp_from_year,
    year_from_url,
)
from helpers.paths import (
    BASE_URL,
    CHAMPIONS_CSV,
    CHAMPIONS_PLAYOFF_ROUNDS_CSV,
    CHAMPIONS_SEASONS_CSV,
    FINALS_MVP_CSV,
    FINALS_SERIES_GAMES_CSV,
    FULL_TOP_8_CSV,
    FULL_TOP_8_UNRANKED_ADVANCED_CSV,
    FULL_TOP_8_UNRANKED_CSV,
    LOGOS_DIR,
    META_DIR,
    OUTPUT_DIR,
    SERIES_TABLES_ADVANCED_WINNER_DIR,
    SERIES_TABLES_DIR,
    SERIES_TABLES_WINNER_DIR,
    TEAM_IDS_SIMPLE_CSV,
)

__all__ = [
    "ADVANCED_FEATURE_COLS",
    "BASE_URL",
    "CHAMPIONS_CSV",
    "CHAMPIONS_PLAYOFF_ROUNDS_CSV",
    "CHAMPIONS_SEASONS_CSV",
    "FINALS_MVP_CSV",
    "FINALS_SERIES_GAMES_CSV",
    "FULL_TOP_8_CSV",
    "FULL_TOP_8_UNRANKED_ADVANCED_CSV",
    "FULL_TOP_8_UNRANKED_CSV",
    "LEAN_MODEL_FEATURE_COLS",
    "LOGOS_DIR",
    "META_DIR",
    "OUTPUT_DIR",
    "SERIES_TABLES_ADVANCED_WINNER_DIR",
    "SERIES_TABLES_DIR",
    "SERIES_TABLES_WINNER_DIR",
    "TEAM_IDS_SIMPLE_CSV",
    "abbrev_from_team",
    "analytic",
    "attach_advanced",
    "baseline_pick",
    "build_finals_series_games",
    "build_top8",
    "champ_from_year",
    "clean_boxscore",
    "control_trial",
    "fetch_image",
    "fix_player_name_encoding",
    "latest_finals_year",
    "list_winner_csvs",
    "load_advanced_features",
    "load_winner_csv",
    "logo",
    "logo_from_seasons_csv",
    "logo_from_team_name",
    "mvp_from_year",
    "name_img",
    "normalize_player_name",
    "rank_table",
    "select_model_features",
    "series_games_from_boxscore",
    "series_games_from_year",
    "softmax_shares",
    "top_table_from_csv",
    "year_from_url",
    "zCol",
    "z_col",
]
