"""Default data paths used across scrapers and the analysis notebook."""

# Parsed tables committed to the repo (source of truth for analysis)
SERIES_TABLES_DIR = "data/series_tables"
SERIES_TABLES_WINNER_DIR = f"{SERIES_TABLES_DIR}/basic/winner"
SERIES_TABLES_LOSER_DIR = f"{SERIES_TABLES_DIR}/basic/loser"
SERIES_TABLES_ADVANCED_WINNER_DIR = f"{SERIES_TABLES_DIR}/advanced/winner"
SERIES_TABLES_ADVANCED_LOSER_DIR = f"{SERIES_TABLES_DIR}/advanced/loser"
META_DIR = "data/meta"
TEAMS_DIR = "data/teams"
OUTPUT_DIR = "output"
LOGOS_DIR = "logos"

FINALS_MVP_CSV = f"{META_DIR}/finals_mvp.csv"
FINALS_SERIES_GAMES_CSV = f"{META_DIR}/finals_series_games.csv"
FINALS_Q4_BY_GAME_CSV = f"{META_DIR}/finals_q4_by_game.csv"
FINALS_Q4_BY_SERIES_CSV = f"{META_DIR}/finals_q4_by_series.csv"
FINALS_WL_EFG_BY_GAME_CSV = f"{META_DIR}/finals_wl_efg_by_game.csv"
FINALS_WL_EFG_BY_SERIES_CSV = f"{META_DIR}/finals_wl_efg_by_series.csv"
FINALS_PTS_CV_BY_SERIES_CSV = f"{META_DIR}/finals_pts_cv_by_series.csv"
FINALS_CLOSEOUT_PTS_BY_SERIES_CSV = f"{META_DIR}/finals_closeout_pts_by_series.csv"
CHAMPIONS_CSV = f"{META_DIR}/champions.csv"
TEAM_IDS_SIMPLE_CSV = f"{META_DIR}/nba_team_ids_simple.csv"
CHAMPIONS_SEASONS_CSV = f"{TEAMS_DIR}/champions_seasons.csv"
CHAMPIONS_PLAYOFF_ROUNDS_CSV = f"{TEAMS_DIR}/champions_playoff_rounds.csv"
FULL_TOP_8_CSV = f"{OUTPUT_DIR}/full_top_8.csv"
FULL_TOP_8_UNRANKED_CSV = f"{OUTPUT_DIR}/full_top_8_unranked.csv"
FULL_TOP_8_UNRANKED_ADVANCED_CSV = f"{OUTPUT_DIR}/full_top_8_unranked_advanced.csv"
FRONTEND_FINALS_JSON = f"{OUTPUT_DIR}/frontend_finals.json"
FEATURE_WEIGHTS_JSON = f"{OUTPUT_DIR}/feature_weights.json"

# Optional scrape caches — gitignored; not required to run the notebook
SERIES_HTML_DIR = "data/series_html"
SERIES_HTML_FINALS_DIR = f"{SERIES_HTML_DIR}/finals"
SERIES_HTML_META_DIR = f"{SERIES_HTML_DIR}/meta"
SERIES_HTML_BOXSCORES_DIR = f"{SERIES_HTML_DIR}/boxscores"
TEAMS_HTML_DIR = f"{TEAMS_DIR}/html"

BASE_URL = "https://www.basketball-reference.com"
